### ISSUE TITLE
A suggestion

### ISSUE THREAD

**Issue by StudyingFather** [MegaOwIer/CNOI-problems#1]
Maybe a website can be made to archive these problems, like [this](https://oi-archive.github.io).

------

也许可以考虑做成一个题目存档网站，像 [这样](https://oi-archive.github.io) 。

**Comment by MegaOwIer** [comment]
Well, I'll try to do that if possible.
<hr></hr>

咕咕咕咕咕那也得我会啊（逃）

**Comment by MegaOwIer** [comment]
Done. You can visit [this page](https://megaowier.github.io/CNOI-problems/) to check if it works.

<hr>

鸽了好久终于想起来了（不是
